---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubetre-controller
rules:
- apiGroups:
  - ""
  resources:
  - limitranges
  - namespaces
  - resourcequotas
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubetre.io
  resources:
  - servicetemplates
  - workspaceservices
  - workspacetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubetre.io
  resources:
  - workspaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubetre.io
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - kubetre.io
  resources:
  - workspaces/status
  - workspaceservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.kubetre.io
  resources:
  - workspacenetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - kubetre-workspace-deployer
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - ocirepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
