apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "desktop.name" . }}-home
  labels: {{- include "desktop.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storageGi }}Gi
