apiVersion: v1
kind: Service
metadata:
  name: {{ include "desktop.name" . }}
  labels: {{- include "desktop.labels" . | nindent 4 }}
spec:
  selector: {{- include "desktop.selector" . | nindent 4 }}
  ports:
    - {name: vnc, port: 5901, targetPort: vnc}
